# Generated by Django 4.1 on 2023-09-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprojectappone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='registration',
            name='last_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(max_length=250),
        ),
    ]
