# Generated by Django 4.1 on 2023-09-07 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprojectappone', '0002_alter_registration_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
